Title="chain33"

[log]
# 日志级别，支持debug(dbug)/info/warn/error(eror)/crit
loglevel = "debug"
logConsoleLevel = "info"
# 日志文件名，可带目录，所有生成的日志文件都放到此目录下
logFile = "logs/chain33.log"
# 单个日志文件的最大值（单位：兆）
maxFileSize = 300
# 最多保存的历史日志文件个数
maxBackups = 100
# 最多保存的历史日志消息（单位：天）
maxAge = 28
# 日志文件名是否使用本地事件（否则使用UTC时间）
localTime = true
# 历史日志文件是否压缩（压缩格式为gz）
compress = true
# 是否打印调用源文件和行号
callerFile = false
# 是否打印调用方法
callerFunction = false


[blockchain]
defCacheSize=512
maxFetchBlockNum=128
timeoutSeconds=5
batchBlockNum=128
driver="leveldb"
dbPath="datadir"
dbCache=256
isStrongConsistency=false
singleMode=false
batchsync=true

[p2p]
seeds=["47.104.125.151:13802","47.104.125.97:13802","47.104.125.177:13802"]
enable=true
isSeed=false
serverStart=true
msgCacheSize=10240
driver="leveldb"
dbPath="datadir/addrbook"
dbCache=16
grpcLogFile="grpc33.log"
version=118
verMix=118
verMax=119

[rpc]
jrpcBindAddr="localhost:8801"
grpcBindAddr="localhost:8802"
whitlist=["127.0.0.1"]

[mempool]
poolCacheSize=10240
minTxFee=100000

[consensus]
name="ticket"
minerstart=true

[store]
name="mavl"
driver="leveldb"
dbPath="datadir/mavltree"
dbCache=128

[wallet]
minFee=100000
driver="leveldb"
dbPath="datadir/wallet"
dbCache=16
signType="secp256k1"

[exec]
isFree=false
minExecFee=100000
