version: "{build}"

# Source Config

clone_folder: c:\gopath\src\github.com\33cn\chain33

# Build host

environment:
  GOPATH: c:\gopath
  DEPTESTBYPASS501: 1
  GOVERSION: 1.9.7

#init:
#  - git config --global core.autocrlf input
# Build

install:
  # Install the specific Go version.
  - rmdir c:\go /s /q
  - appveyor DownloadFile https://dl.google.com/go/go%GOVERSION%.windows-amd64.msi
  - msiexec /i go%GOVERSION%.windows-amd64.msi /q
 # - choco install bzr
  - set Path=c:\go\bin;c:\gopath\bin;C:\Program Files (x86)\Bazaar\;C:\Program Files\Mercurial\%Path%
  - go version
  - go env

build: false
deploy: false

test_script:
  - build.bat
 # - for /f "" %%G in ('go list github.com/33cn/chain33/...') do ( go test %%G & IF ERRORLEVEL == 1 EXIT 1)
